// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmDGdnDZ_JLaLaSqoW_J-DzKdNbK7whY8',
    appId: '1:41063933712:web:b6c729fb091de13bda2795',
    messagingSenderId: '41063933712',
    projectId: 'cyclago-c940e',
    authDomain: 'cyclago-c940e.firebaseapp.com',
    storageBucket: 'cyclago-c940e.firebasestorage.app',
    measurementId: 'G-VLC9BEKBHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACYX0snQtvOnU2ORxLxRA8L5n3pIX6DiI',
    appId: '1:41063933712:android:1fbf2f62e76bcba4da2795',
    messagingSenderId: '41063933712',
    projectId: 'cyclago-c940e',
    storageBucket: 'cyclago-c940e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhsjFtMcLRPVoMgMn3rset1Kb6UMWYQ9Q',
    appId: '1:41063933712:ios:49ae32e10b5108e9da2795',
    messagingSenderId: '41063933712',
    projectId: 'cyclago-c940e',
    storageBucket: 'cyclago-c940e.firebasestorage.app',
    iosBundleId: 'com.example.cyclago',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhsjFtMcLRPVoMgMn3rset1Kb6UMWYQ9Q',
    appId: '1:41063933712:ios:49ae32e10b5108e9da2795',
    messagingSenderId: '41063933712',
    projectId: 'cyclago-c940e',
    storageBucket: 'cyclago-c940e.firebasestorage.app',
    iosBundleId: 'com.example.cyclago',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmDGdnDZ_JLaLaSqoW_J-DzKdNbK7whY8',
    appId: '1:41063933712:web:49ca08d2b8d66d89da2795',
    messagingSenderId: '41063933712',
    projectId: 'cyclago-c940e',
    authDomain: 'cyclago-c940e.firebaseapp.com',
    storageBucket: 'cyclago-c940e.firebasestorage.app',
    measurementId: 'G-YCPVS9SDQG',
  );
}
